name: houmetna_club
description: "Civic reporting mobile app for Houmetna Club."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase packages
  firebase_core: ^2.28.0
  firebase_auth: ^4.20.0
  cloud_firestore: ^4.17.0
  cloud_functions: ^4.6.0

  # UI packages
  google_fonts: ^6.2.1
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
